[project]
authors = ["Matt McCormick <matt@mmmccormick.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "itk-dicom-secondary-capture"
platforms = ["win-64", "linux-64", "linux-aarch64", "osx-arm64"]
version = "0.1.0"

[tasks]
start = "jupyter lab ./itk-dicom-slice-secondary-capture-metadata.ipynb"

[dependencies]
jupyter = ">=1.1.1,<2"
python = ">=3.13.1,<3.14"
pip = ">=24.3.1,<25"
pooch = ">=1.8.2,<2"
tqdm = ">=4.67.1,<5"

[pypi-dependencies]
itk = "==5.4.0"
